config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:index, :show, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/search', :to => 'pages#search'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'

  root :to => 'pages#home'

end

app/views/shared/_auth_home.html.erb
<table class = "front" summary = "For signed-in users">
  <tr>
    <td class = "main">
      <h1 class = "micropost">What's up?</h1>
      <%= render 'shared/micropost_form' %>
      <%= render 'shared/feed' %>
    </tr>
    <td class = "sidebar round">
      <%= render 'shared/user_info' %>
    </td>
  </tr>
</table>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
      from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class = "microposts" summary = "User microposts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class = "gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class = "micropost">
    <span class = "content"><%= wrap(feed_item.content) %></span>
    <%= render 'shared/timestamp', :micropost => feed_item%>
  </td>
  <td class = "delete">
    <% if current_user?(feed_item.user) %>
      <%= link_to "delete", feed_item, :method => :delete,
        :confirm => "You sure?",
        :title => feed_item.content %>
      </td>
    <% end %>
  </tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class = "field">
    <%= f.text_area :content %>
    <span id="characters">140</span>
  </div>
  <div class = "actions">
    <%= f.submit "Submit" %>
  </div>
  <script src = "/javascripts/jquery.js"></script>
  <script>
    window.onload = function() {
      $('textarea').keyup(function() {
        var cs = $(this).val().length;
        $('#characters').text(140-cs);
      });
    }
  </script>
<% end %>

app/views/shared/_no_auth_home.html.erb
<h1>Hey, Stranger.</h1>

<p>Want to sign up?</p>

<%= link_to "Sign Up Here", signup_path, :class => "signup_button round" %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_timestamp.html.erb
<span class = "timestamp">
  <% if controller.controller_name == "microposts" and controller.action_name == "show" %>
    Posted <%= "#{time_ago_in_words(micropost.created_at)}" %> ago:
    <%= "#{micropost.created_at.in_time_zone("Eastern Time (US & Canada)").inspect}" %>
  <% elsif controller.controller_name == "microposts" and controller.action_name == "index" %>
    Posted <%= link_to "#{time_ago_in_words(micropost.created_at)} ago:
    #{micropost.created_at.in_time_zone("Eastern Time (US & Canada)").inspect}", micropost %>
    by <%= link_to micropost.user.name, micropost.user %>
  <% elsif controller.controller_name == "pages" and controller.action_name == "home" %>
    Posted <%= link_to "#{time_ago_in_words(micropost.created_at)} ago", micropost %> by
    <%= link_to micropost.user.name, micropost.user %>
  <% else %>
    Posted <%= link_to "#{time_ago_in_words(micropost.created_at)} ago", micropost %>.
  <% end %>
</span>

app/views/shared/_user_info.html.erb
<div class = "user_info">
  <a href = "<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class = "user_name">
      <%= current_user.name %>
    </span>
    <span class = "microposts">
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
  <%= render 'shared/stats' %>
</div>