config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:index, :show, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/search', :to => 'pages#search'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'

  root :to => 'pages#home'

end

app/views/pages/about.html.erb
<h1>About The Castle</h1>
The castle does not exist.

app/views/pages/contact.html.erb
<h1> Talk To Me </h1>
<p>Don't talk to me.</p>

app/views/pages/help.html.erb
<h1> Help Desk </h1>
<p>Please, no questions.</p>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">What's up?</h1>
        <%= render 'shared/micropost_form' %>
        <%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
      </td>
    </tr>
  </table>
<% else %>
  <h1> Hey, Stranger. </h1>

  <%= link_to "Sign up?", signup_path, :class => "signup_button round" %>
<% end %>

app/views/pages/search.html.erb
<h1>Search</h1>

<table width="100%">
  <tr>
    <th>
      <h3>User Search</h3>
    </th>
    <th>
      <h3>Micropost Search</h3>
    <td>
  </tr>
  <tr>
    <td>
      <%= form_tag users_path, :method => 'get', :class => 'search_form' do %>
        User: <%= text_field_tag :search %>
      <% end %>
    </td>
    <td>
      <%= form_tag microposts_path, :method => 'get', :class => 'search_form' do %>
        Text: <%= text_field_tag :search %>
      <% end %>
    </td>
  </tr>
</table>